/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.4.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as agreeWithOpinion from "../agreeWithOpinion";
import type * as createOpinion from "../createOpinion";
import type * as disagreeWithOpinion from "../disagreeWithOpinion";
import type * as getOpinion from "../getOpinion";
import type * as listOpinions from "../listOpinions";
import type * as starOpinion from "../starOpinion";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  agreeWithOpinion: typeof agreeWithOpinion;
  createOpinion: typeof createOpinion;
  disagreeWithOpinion: typeof disagreeWithOpinion;
  getOpinion: typeof getOpinion;
  listOpinions: typeof listOpinions;
  starOpinion: typeof starOpinion;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
