/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.6.0.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as agreeWithOpinion from "../agreeWithOpinion";
import type * as createOpinion from "../createOpinion";
import type * as disagreeWithOpinion from "../disagreeWithOpinion";
import type * as getOpinion from "../getOpinion";
import type * as listOpinions from "../listOpinions";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  agreeWithOpinion: typeof agreeWithOpinion;
  createOpinion: typeof createOpinion;
  disagreeWithOpinion: typeof disagreeWithOpinion;
  getOpinion: typeof getOpinion;
  listOpinions: typeof listOpinions;
}>;
